### PR TITLE
Bump containerd.io version

### PR DESCRIPTION
**Pull request by schoenr79**
Upgrade containerd from1.2.13-2 -> 1.4.4-1 to a more recent version due to increasing insues with 1.2.13
- Release notes https://github.com/containerd/containerd/releases/tag/v1.4.4

### CODE REVIEW

**Comment by schoenr79** [comment]
@NikolayPianikov could somebody check my PR, or give me some feedback on that. thanks in advance.

**Comment by NikolayPianikov** [comment]
@schoenr79 thank you!

**Comment by schoenr79** [comment]
@NikolayPianikov welcome... what do you think about to move the containerd version to the linux.config. then it is more on the track to update it?
If yes then i will create an improvement issue and submit a another PR.

**Comment by NikolayPianikov** [comment]
@schoenr79 It would be great! Thx

**Pull request merged**
