### PR TITLE
Create/Support Windows Server 2022 (ltsc2022)

### PR DESCRIPTION
**Pull request by Mik4sa**
Followed [these instructions](https://github.com/JetBrains/teamcity-docker-images#to-amend-current-docker-images-or-to-build-your-custom-docker-images-or-create-a-pull-request) to add support for Windows Server 2022 (ltsc2022). The images are tested.

### CODE REVIEW

**Comment by Mik4sa** [comment]
Any update?

**Comment by AndreyKoltsov1997** [comment]
Hello, @Mik4sa!
Thank you very much for the contribution to TeamCity Docker images!
```
The images are tested.
```
I appreciate the verification on your side. As a part of the review process, we would like to perform additional tests on our end, thus both of us would have a strong confidence that the introduced images are matching our quality gates. 
Until verification process is completed, would you, please, synchronize [create-ltsc2022-images](https://github.com/Mik4sa/teamcity-docker-images/tree/create-ltsc2022-images) branch with the latest version of our [master](https://github.com/JetBrains/teamcity-docker-images) branch? Therefore, pull request, as well as the changes within potential merge commit, would be more concise.

**Comment by Mik4sa** [comment]
@AndreyKoltsov1997
Thanks for that. I synchronized (rebased) my branch as requested.

I'm looking forward to a merge :)

Thanks in advance

**Comment by mhoyer** [comment]
Hi. Was there any update on this issue?

**Comment by Mik4sa** [comment]
Not that I would know

**Comment by Mik4sa** [comment]
Windows Server 2022 support was now addressed with #117. We now just need for them to release a new image :)

**Pull request closed without merging**
